@BASE_URL=http://localhost:3333


GET {{BASE_URL}}/pending-goals
Content-Type: application/json
####

GET {{BASE_URL}}/summary
Content-Type: application/json
####


POST {{BASE_URL}}/goals
Content-Type: application/json

{
    "title":"Fazer Exercício", 
    "desiredWeeklyFrequency": 4
}
####


POST {{BASE_URL}}/completions
Content-Type: application/json

{
    "goalId": "u2bcwra4tw65wgl5k3hhc5b4"
}
####